Fix unit test
canonical/charm-nginx pull request #4
Opened 2022-09-21 22:41 UTC by agileshaw

Harness has added validation for checking config options' existence (commit 9a1a5d [1]), which causes error in the unittest. In fact, juju config change only accepts keys that are defined in config.yaml, so the test needs to reflect this.

[1]: https://github.com/canonical/operator/commit/9a1ad5d9a5cd4b84fa40bcb4d9af37553c41b9df#

2022-09-21 22:44 UTC, agileshaw commented
unit test: https://pastebin.canonical.com/p/8Kmwzynpgw/
lint test: https://pastebin.canonical.com/p/cCcXsY4HZ5/

(Currently Ubuntu Pastebin service is down, so the results are pasted to Canonical Pastebin instead)

2022-09-22 16:46 UTC, rgildein requested changes
I think that we should use constants instead of functions here.

2022-09-22 18:35 UTC, rgildein approved these changes
LGTM

2022-09-23 00:27 UTC, Pjack approved these changes

2022-09-23 00:27 UTC, merged